CREATE TABLE EMPLOYEE (
    Fname VARCHAR(50),
    Lname VARCHAR(50),
    SSN INT PRIMARY KEY,
    Addrs VARCHAR(100),
    Sex CHAR(1),
    Salary INT,
    SuperSSN INT,
    Dno INT,
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE DEPARTMENT (
    Dname VARCHAR(50),
    Dnumber INT PRIMARY KEY,
    MgrSSN INT,
    MgrStartDate DATE,
    FOREIGN KEY (MgrSSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE PROJECT (
    Pno INT PRIMARY KEY,
    Pname VARCHAR(100),
    Dnum INT,
    FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE WORKS_ON (
    ESSN INT,
    Pnumber INT,
    Hours INT,
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (Pnumber) REFERENCES PROJECT(Pno)
);


INSERT INTO EMPLOYEE VALUES ('John', 'Doe', 1, '123', 'M', 60000, NULL, 1);
INSERT INTO EMPLOYEE VALUES ('Jane', 'Smith', 2, '456', 'F', 55000, 1, 2);
INSERT INTO EMPLOYEE VALUES ('Alice', 'Johnson', 3, '789', 'F', 52000, 1, 3);
INSERT INTO EMPLOYEE VALUES ('Bob', 'Brown', 4, '101', 'M', 58000, 2, 5);
INSERT INTO EMPLOYEE VALUES ('Michael', 'Davis', 5, '202', 'M', 58000, 2, 5);

-- Insert data into DEPARTMENT table
INSERT INTO DEPARTMENT VALUES ('IT', 1, 1, '2023-01-01');
INSERT INTO DEPARTMENT VALUES ('HR', 2, 4, '2023-01-01');
INSERT INTO DEPARTMENT VALUES ('Fin', 3, 3, '2023-01-01');
INSERT INTO DEPARTMENT VALUES ('Mark', 4, 5, '2023-01-01');
INSERT INTO DEPARTMENT VALUES ('Sales', 5, 2, '2023-01-01');

-- Insert data into PROJECT table
INSERT INTO PROJECT VALUES (1, 'Project A', 1);
INSERT INTO PROJECT VALUES (2, 'Project B', 2);
INSERT INTO PROJECT VALUES (3, 'Project C', 3);
INSERT INTO PROJECT VALUES (4, 'Project D', 4);
INSERT INTO PROJECT VALUES (5, 'Project E', 5);

-- Insert data into WORKS_ON table
INSERT INTO WORKS_ON VALUES (1, 1, 40);
INSERT INTO WORKS_ON VALUES (2, 4, 35);
INSERT INTO WORKS_ON VALUES (1, 2, 45);
INSERT INTO WORKS_ON VALUES (4, 2, 30);
INSERT INTO WORKS_ON VALUES (5, 3, 50);


select * from EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROJECT;
SELECT * FROM WORKS_ON;



#Query-1#
SELECT Fname,Lname
FROM EMPLOYEE
WHERE Salary = (SELECT MAX(Salary) FROM EMPLOYEE WHERE Dno=5);


#Query-2#
SELECT distinct ESSN
FROM WORKS_ON
WHERE Pnumber=1 OR Pnumber=2 OR Pnumber=3;

#Query-3#
SELECT Pnumber,SUM(Hours)
FROM WORKS_ON
GROUP BY Pnumber;
